<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PalworldHelper</AssemblyName>
    <RootNamespace>PalworldHelper</RootNamespace>
    <ApplicationIcon />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SSH.NET" />
  </ItemGroup>
  <ItemGroup Condition="Exists('Embedded/PalworldSaveParser.exe')">
    <EmbeddedResource Include="Embedded/PalworldSaveParser.exe" LogicalName="PalworldHelper.Embedded.PalworldSaveParser.exe" />
  </ItemGroup>
</Project>